package dev.nthings.adf4j.ast;

public sealed interface AdfBlock extends AdfNode
    permits Paragraph,
        Heading,
        Blockquote,
        CodeBlock,
        Panel,
        Rule,
        BulletList,
        OrderedList,
        ListItem,
        TaskList,
        TaskItem,
        BlockTaskItem,
        DecisionList,
        DecisionItem,
        Table,
        TableRow,
        TableCell,
        MediaSingle,
        MediaGroup,
        Media,
        Caption,
        Expand,
        NestedExpand,
        LayoutSection,
        LayoutColumn,
        Extension,
        BodiedExtension,
        MultiBodiedExtension,
        ExtensionFrame,
        SyncBlock,
        BodiedSyncBlock,
        BlockCard,
        EmbedCard,
        UnknownBlock {}
